import createClient from "openapi-fetch";
import type { paths } from "./schema.ts"; // generated by openapi-typescript

export const client = createClient<paths>({ baseUrl: "https://musicfun.it-incubator.app/api/1.0/", headers: {
    'api-key': '0a1c6360-ea6a-430d-a59c-d41a877afc87'
    } });